# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b880d9c9696510632f8568b1ddb3ca4a035bc8be91dc9d924e9df8d4da275c8e09b3d9d0023ec0bbe507e365d3af5dc5c10779d074bda4ea5addedd3dc0520b0

test:
  secret_key_base: 8454b8ebd3d3925722d81378b4e9d4c4069dbdff39c417208b91eb51f69116528844f1262f7b92d532824e8248c7669c085cfa788fccce77fa19e2471708d0b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
